import Foundation
import UIKit

enum WappError: LocalizedError {
    case missingAsset(String)
    case imageEncodingFailed
    case backgroundTooComplex
    case tooManyElements

    var errorDescription: String? {
        switch self {
        case .missingAsset(let name): return String(localized: "Missing bundled asset: \(name)")
        case .imageEncodingFailed: return String(localized: "Could not encode the background image")
        case .backgroundTooComplex:
            return String(localized: "This background is too detailed for the watch — try a simpler or higher-contrast photo.")
        case .tooManyElements:
            return String(localized: "Too much on the face for the watch to draw — remove some complications or live text values, or their goal rings and backgrounds.")
        }
    }
}

/// Builds a Fossil Hybrid HR watchface (.wapp). The container wraps five
/// sections (code, icons, layout, displayName, config); the code section is
/// the author-original `customFace` engine blob and the layout is generated by
/// `CustomFaceLayout` (no precompiled per-widget blobs). The container byte
/// layout is a hardware fact.
struct WappBuilder {
    let design: WatchfaceDesign

    static let watchfaceVersion = (major: 1, minor: 14)   // "1.14" — bumped for customFace.bin's check_start_app

    private func asset(_ name: String, ext: String) throws -> Data {
        guard let url = Bundle.main.url(forResource: name, withExtension: ext, subdirectory: "fossil_hr"),
              let data = try? Data(contentsOf: url)
        else { throw WappError.missingAsset("\(name).\(ext)") }
        return data
    }

    private func widgetCount(_ type: String) -> Int {
        design.widgets.filter { $0.type == type }.count
    }

    /// Text layers with a value source, in design order, paired with their
    /// index among dynamic layers only — this index drives both the
    /// widgetText<i> code-entry name and the glyph asset-name prefix
    /// (GlyphAtlas), independent of any static layers interleaved in
    /// design.textLayers.
    var dynamicTextLayers: [(layer: WatchfaceTextLayer, index: Int)] {
        var index = 0
        return design.textLayers.compactMap { layer in
            guard layer.valueSource != nil else { return nil }
            defer { index += 1 }
            return (layer, index)
        }
    }

    /// Background photo (or plain black) with any text layers baked in —
    /// this is what both background.raw and the preview are encoded from.
    func backgroundImage() -> UIImage {
        let base: UIImage
        if let png = design.backgroundPNG, let image = UIImage(data: png) {
            base = image
        } else {
            // Plain black fallback.
            let renderer = UIGraphicsImageRenderer(size: CGSize(width: 240, height: 240))
            base = renderer.image { context in
                UIColor.black.setFill()
                context.fill(CGRect(x: 0, y: 0, width: 240, height: 240))
            }
        }
        return TextLayerRenderer.composite(background: base, layers: design.textLayers)
    }

    func build() throws -> Data {
        let name = design.sanitizedName
        let background = backgroundImage()
        guard let backgroundRaw = ImageEncoder.backgroundRaw(from: background),
              let backgroundRLE = ImageEncoder.backgroundRLE(from: background),
              let previewRLE = ImageEncoder.previewRLE(from: background)
        else { throw WappError.imageEncodingFailed }
        // A section entry's length is a u16 — a very busy photo could RLE past
        // 64 KB. Raw is fixed 14 KB but the layout parser can't draw it, so
        // fail clearly rather than trap packing an oversized entry.
        guard backgroundRLE.count <= 0xFFFE else { throw WappError.backgroundTooComplex }

        let generated = CustomFaceLayout.generate(for: design)
        // Too many layout nodes make the firmware render a blank screen — fail
        // clearly at build time rather than shipping a face that won't display.
        #if DEBUG
        print("face has \(generated.layout.count) nodes")
        #endif
        guard generated.layout.count <= CustomFaceLayout.maxNodes else {
            throw WappError.tooManyElements
        }

        // --- code section: the single author-original customFace engine blob,
        // keyed under the face's own name (the watch loads the code entry whose
        // name matches the face). No per-widget blobs. ---
        let code: [(String, Data)] = [(name, try asset("customFace", ext: "bin"))]

        // --- icons section: background + preview + the static complication
        // icons this design references (dynamic battery/weather icons pack the
        // whole family) + per-widget background circles. Icon *names* are
        // unchanged from before; only the bytes are now author-original. ---
        var icons: [(String, Data)] = []
        icons.append(("background", backgroundRLE))     // drawn by the customFace layout image node
        icons.append(("background.raw", backgroundRaw)) // kept for WappReader's downloaded-face preview
        icons.append(("!preview.rle", previewRLE))
        // Exactly the complication icons the generated layout references
        // (color-matched; dynamic weather/battery families included).
        for iconName in generated.iconAssets.sorted() {
            icons.append((iconName, try asset(iconName, ext: "rle")))
        }
        // Baked custom-font glyph atlases for dynamic text layers.
        for glyph in generated.glyphImages {
            icons.append((glyph.name, glyph.rle))
        }
        var backgroundNames = Set<String>()
        for widget in design.widgets {
            guard let rleName = widget.backgroundRLEName, backgroundNames.insert(rleName).inserted else { continue }
            guard let rle = ImageEncoder.widgetBackgroundRLE(
                circleNamed: widget.background.isEmpty ? nil : widget.background,
                solidFill: widget.wantsSolidFill,
                inverted: widget.color == 1)
            else { throw WappError.missingAsset("\(widget.background).png") }
            icons.append((rleName, rle))
        }

        // --- layout section: the single generated node tree customFace draws ---
        let layoutData = try JSONSerialization.data(withJSONObject: generated.layout)
        let layout: [(String, Data)] = [(CustomFaceLayout.layoutName, layoutData)]

        // --- displayName + config sections ---
        let displayName: [(String, String)] = [
            ("display_name", name),
            ("theme_class", "complications"),
        ]
        let config: [(String, String)] = [
            ("customWatchFace", try configurationJSON(generated: generated)),
        ]

        return Self.assembleWapp(version: Self.watchfaceVersion,
                                 code: code,
                                 icons: icons,
                                 layout: layout,
                                 displayName: displayName,
                                 config: config)
    }

    /// The "customWatchFace" config JSON: the customFace field map + on-watch
    /// behavior settings + a compact `widgets` metadata array so an installed
    /// face can be read back for re-editing (WappReader.widgets).
    private func configurationJSON(generated: CustomFaceLayout.Result) throws -> String {
        // System-level behavior block (read by the firmware, not the JS).
        let config: [String: Any] = [
            "timeout_display_full": 60 * 60 * 1000,
            "timeout_display_partial": 15 * 60 * 1000,
            "wrist_flick_hands_relative": true,
            "wrist_flick_duration": 2200,
            "wrist_flick_move_hour": 360,
            "wrist_flick_move_minute": -360,
            "move_hands_event": "flick_away",
            "powersave_display": false,
            "powersave_hands": false,
            "light_up_on_notification": false,
        ]

        var configuration: [String: Any] = [:]
        configuration["fields"] = generated.fields
        configuration["config"] = config
        configuration["widgets"] = generated.widgetMeta
        configuration["text_layers"] = generated.textLayerMeta

        let data = try JSONSerialization.data(withJSONObject: configuration)
        return String(data: data, encoding: .utf8) ?? "{}"
    }

    // MARK: Container assembly (FossilAppWriter port)

    static func assembleWapp(version: (major: Int, minor: Int),
                             code: [(String, Data)],
                             icons: [(String, Data)],
                             layout: [(String, Data)],
                             displayName: [(String, String)],
                             config: [(String, String)]) -> Data {
        let codeData = packEntries(code, appendNull: false)
        let iconsData = packEntries(icons, appendNull: false)
        let layoutData = packEntries(layout, appendNull: true)
        let displayNameData = packStringEntries(displayName)
        let configData = packStringEntries(config)

        // Section offsets are absolute from byte 0 of the final file,
        // including the 12-byte transport header below (hence code = 88 =
        // 12 + 76-byte inner header).
        let offsetCode = 88
        let offsetIcons = offsetCode + codeData.count
        let offsetLayout = offsetIcons + iconsData.count
        let offsetDisplayName = offsetLayout + layoutData.count
        let offsetConfig = offsetDisplayName + displayNameData.count
        let offsetFileEnd = offsetConfig + configData.count

        var filePart = Data()
        filePart.append(0x01)                       // 1 = watchface, 2 = app
        filePart.append(UInt8(version.major))
        filePart.append(UInt8(version.minor))
        filePart.append(0x00)
        filePart.appendUInt32LE(0)
        filePart.appendUInt32LE(0)
        filePart.appendUInt32LE(UInt32(offsetCode))
        filePart.appendUInt32LE(UInt32(offsetIcons))
        filePart.appendUInt32LE(UInt32(offsetLayout))
        filePart.appendUInt32LE(UInt32(offsetDisplayName))
        filePart.appendUInt32LE(UInt32(offsetDisplayName))
        filePart.appendUInt32LE(UInt32(offsetConfig))
        filePart.appendUInt32LE(UInt32(offsetFileEnd))
        for _ in 0..<9 { filePart.appendUInt32LE(0) }
        filePart.append(codeData)
        filePart.append(iconsData)
        filePart.append(layoutData)
        filePart.append(displayNameData)
        filePart.append(configData)

        var wapp = Data()
        wapp.append(contentsOf: [0xFE, 0x15])       // APP_CODE handle, LE
        wapp.append(contentsOf: [0x03, 0x00])       // file version
        wapp.appendUInt32LE(0)                      // file offset
        wapp.appendUInt32LE(UInt32(filePart.count))
        wapp.append(filePart)
        wapp.appendUInt32LE(Checksums.crc32c(filePart))
        return wapp
    }

    static func packEntries(_ entries: [(String, Data)], appendNull: Bool) -> Data {
        var out = Data()
        for (name, content) in entries {
            let nameBytes = name.nullTerminatedUTF8()
            out.append(UInt8(nameBytes.count))
            out.append(nameBytes)
            out.appendUInt16LE(UInt16(content.count + (appendNull ? 1 : 0)))
            out.append(content)
            if appendNull { out.append(0x00) }
        }
        return out
    }

    static func packStringEntries(_ entries: [(String, String)]) -> Data {
        var out = Data()
        for (name, value) in entries {
            let nameBytes = name.nullTerminatedUTF8()
            let valueBytes = value.nullTerminatedUTF8(maxLength: Int(UInt16.max))
            out.append(UInt8(nameBytes.count))
            out.append(nameBytes)
            out.appendUInt16LE(UInt16(valueBytes.count))
            out.append(valueBytes)
        }
        return out
    }

    /// Why a `.wapp` could not be re-labelled. Each case names the specific
    /// assumption the file broke, because the rescue only gets one shot per
    /// reboot window and "returned nil" costs a whole one.
    enum WappRenameError: Error, CustomStringConvertible {
        case notAContainer(String)
        case checksumNotCRC32C
        case noIdentifier
        case badName(String)
        case verificationFailed(String)

        var description: String {
            switch self {
            case .notAContainer(let detail): "not a .wapp container (\(detail))"
            case .checksumNotCRC32C: "trailing checksum isn't CRC32C — re-labelling would corrupt it"
            case .noIdentifier: "no readable identifier in the code section"
            case .badName(let name): "unusable replacement identifier \"\(name)\""
            case .verificationFailed(let detail): "rewritten file failed verification (\(detail))"
            }
        }
    }

    /// Rewrites a container's identifier — the name of the first code-section
    /// entry, which is what the watch lists and what it keys an installed app
    /// by. Everything else is preserved byte for byte.
    ///
    /// This exists for the watchface rescue. A watch that has stopped
    /// answering `delete` still accepts an install on the APP_CODE handle
    /// (a put straight to an app's *own* slot is refused: "not supported"), so
    /// the only way to replace broken code in a slot is to install a healthy
    /// face carrying the broken one's identifier.
    ///
    /// The identifier's length is part of the file: every absolute offset in
    /// the inner header's table, the transport header's payload length and the
    /// trailing CRC32C all move with it. The code section itself is the first
    /// section and never shifts.
    ///
    /// Deliberately *not* gated on `WappReader.isValidContainer`: that check
    /// encodes what our own builder emits (exactly seven used offset slots,
    /// the last one being the end of the file), and a stock Fossil face is not
    /// obliged to lay its header out that way — the first attempt on one
    /// returned nil for that reason alone. What is checked here is only what
    /// this rewrite actually depends on: the transport envelope, a trailing
    /// CRC32C that already matches (otherwise recomputing one would produce a
    /// file the watch rejects), and a readable identifier. Every offset slot
    /// pointing past the code section is shifted, whichever slots those are.
    static func renamingIdentifier(in wapp: Data, to newIdentifier: String) throws -> Data {
        guard wapp.count >= 92, wapp.count <= WappReader.maxContainerSize,
              wapp.u16LE(at: 0) == FossilFileHandle.appCode.rawValue, wapp.u32LE(at: 4) == 0 else {
            throw WappRenameError.notAContainer("size \(wapp.count), handle 0x\(String(format: "%04X", Int(wapp.count >= 2 ? wapp.u16LE(at: 0) : 0)))")
        }
        let payloadLength = Int(wapp.u32LE(at: 8))
        guard payloadLength >= 76, 12 + payloadLength + 4 == wapp.count else {
            throw WappRenameError.notAContainer("declared payload \(payloadLength), file \(wapp.count)")
        }
        guard wapp.u32LE(at: 12 + payloadLength) == Checksums.crc32c(wapp.slice(12, payloadLength)) else {
            throw WappRenameError.checksumNotCRC32C
        }
        guard let oldIdentifier = WappReader.identifier(fromWapp: wapp) else {
            throw WappRenameError.noIdentifier
        }
        if oldIdentifier == newIdentifier { return wapp }
        let newNameBytes = newIdentifier.nullTerminatedUTF8()
        guard newNameBytes.count > 1, newNameBytes.count <= Int(UInt8.max) else {
            throw WappRenameError.badName(newIdentifier)
        }

        let codeStart = Int(wapp.u32LE(at: 24))
        let oldNameLength = Int(wapp.u8(at: codeStart))     // includes the null
        let delta = newNameBytes.count - oldNameLength

        var out = Data()
        out.append(wapp.slice(0, codeStart))                // header + offsets
        out.append(UInt8(newNameBytes.count))
        out.append(newNameBytes)
        // Everything after the old name, unchanged.
        let tailStart = codeStart + 1 + oldNameLength
        out.append(wapp.slice(tailStart, wapp.count - 4 - tailStart))

        // Shift every offset slot that points past the code section — unused
        // slots hold 0 and the code offset equals `codeStart`, so both are
        // left alone by the same comparison.
        for field in stride(from: 16, through: 12 + 76 - 4, by: 4) {
            let value = Int(out.u32LE(at: field))
            if value > codeStart { patchU32(&out, at: field, UInt32(value + delta)) }
        }
        let patchedLength = UInt32(payloadLength + delta)
        patchU32(&out, at: 8, patchedLength)
        out.appendUInt32LE(Checksums.crc32c(out.slice(12, Int(patchedLength))))

        guard WappReader.identifier(fromWapp: out) == newIdentifier else {
            throw WappRenameError.verificationFailed("identifier reads back as " +
                                                     "\(WappReader.identifier(fromWapp: out) ?? "nil")")
        }
        return out
    }

    /// One-line dump of a container's header, so a rename that can't proceed
    /// says *why* in the log instead of just failing.
    static func containerSummary(_ wapp: Data) -> String {
        guard wapp.count >= 92 else { return "only \(wapp.count) bytes" }
        let payloadLength = Int(wapp.u32LE(at: 8))
        let crcOK = 12 + payloadLength + 4 == wapp.count
            && wapp.u32LE(at: 12 + payloadLength) == Checksums.crc32c(wapp.slice(12, payloadLength))
        let offsets = stride(from: 24, through: 84, by: 4)
            .map { Int(wapp.u32LE(at: $0)) }
            .prefix(while: { _ in true })
        return "size \(wapp.count), payload \(payloadLength), type \(wapp.u8(at: 12)), " +
               "crc32c \(crcOK ? "ok" : "MISMATCH"), " +
               "identifier \(WappReader.identifier(fromWapp: wapp) ?? "nil"), " +
               "offsets \(offsets.map(String.init).joined(separator: ","))"
    }

    /// Offset-relative u32 overwrite, matching `u32LE(at:)`'s indexing.
    private static func patchU32(_ data: inout Data, at offset: Int, _ value: UInt32) {
        let start = data.startIndex + offset
        data.replaceSubrange(start..<(start + 4), with: [
            UInt8(value & 0xFF), UInt8((value >> 8) & 0xFF),
            UInt8((value >> 16) & 0xFF), UInt8((value >> 24) & 0xFF),
        ])
    }
}
